; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BB2C4585-E935-44EC-91AA-3B056396E736}
AppName=Asteroid
AppVersion=1.1.0
;AppVerName=Asteroid 1.1.0
AppPublisher=JJaeWook.c
AppPublisherURL=http://www.example.com/
AppSupportURL=http://www.example.com/
AppUpdatesURL=http://www.example.com/
DefaultDirName={pf}\Asteroid
DefaultGroupName=Asteroid
OutputDir=C:\Users\Mado\Desktop
OutputBaseFilename=Asteroid_Setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\2DGP\2DGP\Asteroid\dist\game_start.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\2DGP\2DGP\Asteroid\dist\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Asteroid"; Filename: "{app}\game_start.exe"
Name: "{commondesktop}\Asteroid"; Filename: "{app}\game_start.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\game_start.exe"; Description: "{cm:LaunchProgram,Asteroid}"; Flags: nowait postinstall skipifsilent

